///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class AyatResponseDataAyatAudio {
/*
{
  "01": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdullah-Al-Juhany/001001.mp3",
  "02": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdul-Muhsin-Al-Qasim/001001.mp3",
  "03": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdurrahman-as-Sudais/001001.mp3",
  "04": "https://equran.nos.wjv-1.neo.id/audio-partial/Ibrahim-Al-Dossari/001001.mp3",
  "05": "https://equran.nos.wjv-1.neo.id/audio-partial/Misyari-Rasyid-Al-Afasi/001001.mp3"
} 
*/

  String? the01;
  String? the02;
  String? the03;
  String? the04;
  String? the05;

  AyatResponseDataAyatAudio({
    this.the01,
    this.the02,
    this.the03,
    this.the04,
    this.the05,
  });
  AyatResponseDataAyatAudio.fromJson(Map<String, dynamic> json) {
    the01 = json['01']?.toString();
    the02 = json['02']?.toString();
    the03 = json['03']?.toString();
    the04 = json['04']?.toString();
    the05 = json['05']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['01'] = the01;
    data['02'] = the02;
    data['03'] = the03;
    data['04'] = the04;
    data['05'] = the05;
    return data;
  }
}

class AyatResponseDataAyat {
/*
{
  "nomorAyat": 1,
  "teksArab": "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
  "teksLatin": "bismillāhir-raḥmānir-raḥīm(i).",
  "teksIndonesia": "Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.",
  "audio": {
    "01": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdullah-Al-Juhany/001001.mp3",
    "02": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdul-Muhsin-Al-Qasim/001001.mp3",
    "03": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdurrahman-as-Sudais/001001.mp3",
    "04": "https://equran.nos.wjv-1.neo.id/audio-partial/Ibrahim-Al-Dossari/001001.mp3",
    "05": "https://equran.nos.wjv-1.neo.id/audio-partial/Misyari-Rasyid-Al-Afasi/001001.mp3"
  }
} 
*/

  int? nomorAyat;
  String? teksArab;
  String? teksLatin;
  String? teksIndonesia;
  AyatResponseDataAyatAudio? audio;

  AyatResponseDataAyat({
    this.nomorAyat,
    this.teksArab,
    this.teksLatin,
    this.teksIndonesia,
    this.audio,
  });
  AyatResponseDataAyat.fromJson(Map<String, dynamic> json) {
    nomorAyat = int.tryParse(json['nomorAyat']?.toString() ?? '');
    teksArab = json['teksArab']?.toString();
    teksLatin = json['teksLatin']?.toString();
    teksIndonesia = json['teksIndonesia']?.toString();
    audio = (json['audio'] != null && (json['audio'] is Map)) ? AyatResponseDataAyatAudio.fromJson(json['audio']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nomorAyat'] = nomorAyat;
    data['teksArab'] = teksArab;
    data['teksLatin'] = teksLatin;
    data['teksIndonesia'] = teksIndonesia;
    if (audio != null) {
      data['audio'] = audio!.toJson();
    }
    return data;
  }
}

class AyatResponseDataAudioFull {
/*
{
  "01": "https://equran.nos.wjv-1.neo.id/audio-full/Abdullah-Al-Juhany/001.mp3",
  "02": "https://equran.nos.wjv-1.neo.id/audio-full/Abdul-Muhsin-Al-Qasim/001.mp3",
  "03": "https://equran.nos.wjv-1.neo.id/audio-full/Abdurrahman-as-Sudais/001.mp3",
  "04": "https://equran.nos.wjv-1.neo.id/audio-full/Ibrahim-Al-Dossari/001.mp3",
  "05": "https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/001.mp3"
} 
*/

  String? the01;
  String? the02;
  String? the03;
  String? the04;
  String? the05;

  AyatResponseDataAudioFull({
    this.the01,
    this.the02,
    this.the03,
    this.the04,
    this.the05,
  });
  AyatResponseDataAudioFull.fromJson(Map<String, dynamic> json) {
    the01 = json['01']?.toString();
    the02 = json['02']?.toString();
    the03 = json['03']?.toString();
    the04 = json['04']?.toString();
    the05 = json['05']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['01'] = the01;
    data['02'] = the02;
    data['03'] = the03;
    data['04'] = the04;
    data['05'] = the05;
    return data;
  }
}

class AyatResponseData {
/*
{
  "nomor": 1,
  "nama": "الفاتحة",
  "namaLatin": "Al-Fatihah",
  "jumlahAyat": 7,
  "tempatTurun": "Mekah",
  "arti": "Pembukaan",
  "deskripsi": "Surat <i>Al Faatihah</i> (Pembukaan) yang diturunkan di Mekah dan terdiri dari 7 ayat adalah surat yang pertama-tama diturunkan dengan lengkap  diantara surat-surat yang ada dalam Al Quran dan termasuk golongan surat Makkiyyah. Surat ini disebut <i>Al Faatihah</i> (Pembukaan), karena dengan surat inilah dibuka dan dimulainya Al Quran. Dinamakan <i>Ummul Quran</i> (induk Al Quran) atau <i>Ummul Kitaab</i> (induk Al Kitaab) karena dia merupakan induk dari semua isi Al Quran, dan karena itu diwajibkan membacanya pada tiap-tiap sembahyang.<br> Dinamakan pula <i>As Sab'ul matsaany</i> (tujuh yang berulang-ulang) karena ayatnya tujuh dan dibaca berulang-ulang dalam sholat.",
  "audioFull": {
    "01": "https://equran.nos.wjv-1.neo.id/audio-full/Abdullah-Al-Juhany/001.mp3",
    "02": "https://equran.nos.wjv-1.neo.id/audio-full/Abdul-Muhsin-Al-Qasim/001.mp3",
    "03": "https://equran.nos.wjv-1.neo.id/audio-full/Abdurrahman-as-Sudais/001.mp3",
    "04": "https://equran.nos.wjv-1.neo.id/audio-full/Ibrahim-Al-Dossari/001.mp3",
    "05": "https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/001.mp3"
  },
  "ayat": [
    {
      "nomorAyat": 1,
      "teksArab": "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
      "teksLatin": "bismillāhir-raḥmānir-raḥīm(i).",
      "teksIndonesia": "Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.",
      "audio": {
        "01": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdullah-Al-Juhany/001001.mp3",
        "02": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdul-Muhsin-Al-Qasim/001001.mp3",
        "03": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdurrahman-as-Sudais/001001.mp3",
        "04": "https://equran.nos.wjv-1.neo.id/audio-partial/Ibrahim-Al-Dossari/001001.mp3",
        "05": "https://equran.nos.wjv-1.neo.id/audio-partial/Misyari-Rasyid-Al-Afasi/001001.mp3"
      }
    }
  ],
  "suratSelanjutnya": {
    "nomor": 2,
    "nama": "البقرة",
    "namaLatin": "Al-Baqarah",
    "jumlahAyat": 286
  },
  "suratSebelumnya": false
} 
*/

  int? nomor;
  String? nama;
  String? namaLatin;
  int? jumlahAyat;
  String? tempatTurun;
  String? arti;
  String? deskripsi;
  AyatResponseDataAudioFull? audioFull;
  List<AyatResponseDataAyat?>? ayat;

  AyatResponseData({
    this.nomor,
    this.nama,
    this.namaLatin,
    this.jumlahAyat,
    this.tempatTurun,
    this.arti,
    this.deskripsi,
    this.audioFull,
    this.ayat,
  });
  AyatResponseData.fromJson(Map<String, dynamic> json) {
    nomor = int.tryParse(json['nomor']?.toString() ?? '');
    nama = json['nama']?.toString();
    namaLatin = json['namaLatin']?.toString();
    jumlahAyat = int.tryParse(json['jumlahAyat']?.toString() ?? '');
    tempatTurun = json['tempatTurun']?.toString();
    arti = json['arti']?.toString();
    deskripsi = json['deskripsi']?.toString();
    audioFull = (json['audioFull'] != null && (json['audioFull'] is Map)) ? AyatResponseDataAudioFull.fromJson(json['audioFull']) : null;
  if (json['ayat'] != null && (json['ayat'] is List)) {
  final v = json['ayat'];
  final arr0 = <AyatResponseDataAyat>[];
  v.forEach((v) {
  arr0.add(AyatResponseDataAyat.fromJson(v));
  });
    ayat = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nomor'] = nomor;
    data['nama'] = nama;
    data['namaLatin'] = namaLatin;
    data['jumlahAyat'] = jumlahAyat;
    data['tempatTurun'] = tempatTurun;
    data['arti'] = arti;
    data['deskripsi'] = deskripsi;
    if (audioFull != null) {
      data['audioFull'] = audioFull!.toJson();
    }
    if (ayat != null) {
      final v = ayat;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['ayat'] = arr0;
    }
    return data;
  }
}

class AyatResponse {
/*
{
  "code": 200,
  "message": "Data retrieved successfully",
  "data": {
    "nomor": 1,
    "nama": "الفاتحة",
    "namaLatin": "Al-Fatihah",
    "jumlahAyat": 7,
    "tempatTurun": "Mekah",
    "arti": "Pembukaan",
    "deskripsi": "Surat <i>Al Faatihah</i> (Pembukaan) yang diturunkan di Mekah dan terdiri dari 7 ayat adalah surat yang pertama-tama diturunkan dengan lengkap  diantara surat-surat yang ada dalam Al Quran dan termasuk golongan surat Makkiyyah. Surat ini disebut <i>Al Faatihah</i> (Pembukaan), karena dengan surat inilah dibuka dan dimulainya Al Quran. Dinamakan <i>Ummul Quran</i> (induk Al Quran) atau <i>Ummul Kitaab</i> (induk Al Kitaab) karena dia merupakan induk dari semua isi Al Quran, dan karena itu diwajibkan membacanya pada tiap-tiap sembahyang.<br> Dinamakan pula <i>As Sab'ul matsaany</i> (tujuh yang berulang-ulang) karena ayatnya tujuh dan dibaca berulang-ulang dalam sholat.",
    "audioFull": {
      "01": "https://equran.nos.wjv-1.neo.id/audio-full/Abdullah-Al-Juhany/001.mp3",
      "02": "https://equran.nos.wjv-1.neo.id/audio-full/Abdul-Muhsin-Al-Qasim/001.mp3",
      "03": "https://equran.nos.wjv-1.neo.id/audio-full/Abdurrahman-as-Sudais/001.mp3",
      "04": "https://equran.nos.wjv-1.neo.id/audio-full/Ibrahim-Al-Dossari/001.mp3",
      "05": "https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/001.mp3"
    },
    "ayat": [
      {
        "nomorAyat": 1,
        "teksArab": "بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ",
        "teksLatin": "bismillāhir-raḥmānir-raḥīm(i).",
        "teksIndonesia": "Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.",
        "audio": {
          "01": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdullah-Al-Juhany/001001.mp3",
          "02": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdul-Muhsin-Al-Qasim/001001.mp3",
          "03": "https://equran.nos.wjv-1.neo.id/audio-partial/Abdurrahman-as-Sudais/001001.mp3",
          "04": "https://equran.nos.wjv-1.neo.id/audio-partial/Ibrahim-Al-Dossari/001001.mp3",
          "05": "https://equran.nos.wjv-1.neo.id/audio-partial/Misyari-Rasyid-Al-Afasi/001001.mp3"
        }
      }
    ],
    "suratSelanjutnya": {
      "nomor": 2,
      "nama": "البقرة",
      "namaLatin": "Al-Baqarah",
      "jumlahAyat": 286
    },
    "suratSebelumnya": false
  }
} 
*/

  int? code;
  String? message;
  AyatResponseData? data;

  AyatResponse({
    this.code,
    this.message,
    this.data,
  });
  AyatResponse.fromJson(Map<String, dynamic> json) {
    code = int.tryParse(json['code']?.toString() ?? '');
    message = json['message']?.toString();
    data = (json['data'] != null && (json['data'] is Map)) ? AyatResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['message'] = message;
    data['data'] = this.data!.toJson();
    return data;
  }
}
