///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SuratResponseDataAudioFull {
/*
{
  "01": "https://equran.nos.wjv-1.neo.id/audio-full/Abdullah-Al-Juhany/001.mp3",
  "02": "https://equran.nos.wjv-1.neo.id/audio-full/Abdul-Muhsin-Al-Qasim/001.mp3",
  "03": "https://equran.nos.wjv-1.neo.id/audio-full/Abdurrahman-as-Sudais/001.mp3",
  "04": "https://equran.nos.wjv-1.neo.id/audio-full/Ibrahim-Al-Dossari/001.mp3",
  "05": "https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/001.mp3"
} 
*/

  String? the01;
  String? the02;
  String? the03;
  String? the04;
  String? the05;

  SuratResponseDataAudioFull({
    this.the01,
    this.the02,
    this.the03,
    this.the04,
    this.the05,
  });
  SuratResponseDataAudioFull.fromJson(Map<String, dynamic> json) {
    the01 = json['01']?.toString();
    the02 = json['02']?.toString();
    the03 = json['03']?.toString();
    the04 = json['04']?.toString();
    the05 = json['05']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['01'] = the01;
    data['02'] = the02;
    data['03'] = the03;
    data['04'] = the04;
    data['05'] = the05;
    return data;
  }
}

class SuratResponseData {
/*
{
  "nomor": 1,
  "nama": "الفاتحة",
  "namaLatin": "Al-Fatihah",
  "jumlahAyat": 7,
  "tempatTurun": "Mekah",
  "arti": "Pembukaan",
  "deskripsi": "Surat <i>Al Faatihah</i> (Pembukaan) yang diturunkan di Mekah dan terdiri dari 7 ayat adalah surat yang pertama-tama diturunkan dengan lengkap  diantara surat-surat yang ada dalam Al Quran dan termasuk golongan surat Makkiyyah. Surat ini disebut <i>Al Faatihah</i> (Pembukaan), karena dengan surat inilah dibuka dan dimulainya Al Quran. Dinamakan <i>Ummul Quran</i> (induk Al Quran) atau <i>Ummul Kitaab</i> (induk Al Kitaab) karena dia merupakan induk dari semua isi Al Quran, dan karena itu diwajibkan membacanya pada tiap-tiap sembahyang.<br> Dinamakan pula <i>As Sab'ul matsaany</i> (tujuh yang berulang-ulang) karena ayatnya tujuh dan dibaca berulang-ulang dalam sholat.",
  "audioFull": {
    "01": "https://equran.nos.wjv-1.neo.id/audio-full/Abdullah-Al-Juhany/001.mp3",
    "02": "https://equran.nos.wjv-1.neo.id/audio-full/Abdul-Muhsin-Al-Qasim/001.mp3",
    "03": "https://equran.nos.wjv-1.neo.id/audio-full/Abdurrahman-as-Sudais/001.mp3",
    "04": "https://equran.nos.wjv-1.neo.id/audio-full/Ibrahim-Al-Dossari/001.mp3",
    "05": "https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/001.mp3"
  }
} 
*/

  int? nomor;
  String? nama;
  String? namaLatin;
  int? jumlahAyat;
  String? tempatTurun;
  String? arti;
  String? deskripsi;
  SuratResponseDataAudioFull? audioFull;

  SuratResponseData({
    this.nomor,
    this.nama,
    this.namaLatin,
    this.jumlahAyat,
    this.tempatTurun,
    this.arti,
    this.deskripsi,
    this.audioFull,
  });
  SuratResponseData.fromJson(Map<String, dynamic> json) {
    nomor = int.tryParse(json['nomor']?.toString() ?? '');
    nama = json['nama']?.toString();
    namaLatin = json['namaLatin']?.toString();
    jumlahAyat = int.tryParse(json['jumlahAyat']?.toString() ?? '');
    tempatTurun = json['tempatTurun']?.toString();
    arti = json['arti']?.toString();
    deskripsi = json['deskripsi']?.toString();
    audioFull = (json['audioFull'] != null && (json['audioFull'] is Map)) ? SuratResponseDataAudioFull.fromJson(json['audioFull']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nomor'] = nomor;
    data['nama'] = nama;
    data['namaLatin'] = namaLatin;
    data['jumlahAyat'] = jumlahAyat;
    data['tempatTurun'] = tempatTurun;
    data['arti'] = arti;
    data['deskripsi'] = deskripsi;
    if (audioFull != null) {
      data['audioFull'] = audioFull!.toJson();
    }
    return data;
  }
}

class SuratResponse {
/*
{
  "code": 200,
  "message": "Data retrieved successfully",
  "data": [
    {
      "nomor": 1,
      "nama": "الفاتحة",
      "namaLatin": "Al-Fatihah",
      "jumlahAyat": 7,
      "tempatTurun": "Mekah",
      "arti": "Pembukaan",
      "deskripsi": "Surat <i>Al Faatihah</i> (Pembukaan) yang diturunkan di Mekah dan terdiri dari 7 ayat adalah surat yang pertama-tama diturunkan dengan lengkap  diantara surat-surat yang ada dalam Al Quran dan termasuk golongan surat Makkiyyah. Surat ini disebut <i>Al Faatihah</i> (Pembukaan), karena dengan surat inilah dibuka dan dimulainya Al Quran. Dinamakan <i>Ummul Quran</i> (induk Al Quran) atau <i>Ummul Kitaab</i> (induk Al Kitaab) karena dia merupakan induk dari semua isi Al Quran, dan karena itu diwajibkan membacanya pada tiap-tiap sembahyang.<br> Dinamakan pula <i>As Sab'ul matsaany</i> (tujuh yang berulang-ulang) karena ayatnya tujuh dan dibaca berulang-ulang dalam sholat.",
      "audioFull": {
        "01": "https://equran.nos.wjv-1.neo.id/audio-full/Abdullah-Al-Juhany/001.mp3",
        "02": "https://equran.nos.wjv-1.neo.id/audio-full/Abdul-Muhsin-Al-Qasim/001.mp3",
        "03": "https://equran.nos.wjv-1.neo.id/audio-full/Abdurrahman-as-Sudais/001.mp3",
        "04": "https://equran.nos.wjv-1.neo.id/audio-full/Ibrahim-Al-Dossari/001.mp3",
        "05": "https://equran.nos.wjv-1.neo.id/audio-full/Misyari-Rasyid-Al-Afasi/001.mp3"
      }
    }
  ]
} 
*/

  int? code;
  String? message;
  List<SuratResponseData?>? data;

  SuratResponse({
    this.code,
    this.message,
    this.data,
  });
  SuratResponse.fromJson(Map<String, dynamic> json) {
    code = int.tryParse(json['code']?.toString() ?? '');
    message = json['message']?.toString();
  if (json['data'] != null && (json['data'] is List)) {
  final v = json['data'];
  final arr0 = <SuratResponseData>[];
  v.forEach((v) {
  arr0.add(SuratResponseData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
